language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8

before_install:
  - env

install:
  - pip install --upgrade pip
  - pip install coverage
  - python setup.py install
  - pip install coveralls

script:
  - nosetests --with-doctest --with-coverage --cover-tests --cover-package=pyslice --cover-branches --cover-erase

after_success:
  - coveralls
